import type { Metadata } from "next";
import { Tinos } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../../components/theme-provider";

const tinos = Tinos({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Ethical Infrastructure",
  description: "Generated by create next app",
  // ✅ Add Google site verification here
  other: {
    "google-site-verification": "Q1CXFjS4LoeATJZZmDq3iUY5hpOgG2_16oPF_DVp_h0",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* ✅ Extra safety: meta tag explicitly added here */}
        <meta
          name="google-site-verification"
          content="Q1CXFjS4LoeATJZZmDq3iUY5hpOgG2_16oPF_DVp_h0"
        />
      </head>
      <body className={`${tinos.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
