import type { Metadata } from "next";
import { Tinos } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../../components/theme-provider";
import Script from "next/script"; // ✅ Import Script from Next.js

const tinos = Tinos({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Ethical Infrastructure",
  description: "Generated by create next app",
  other: {
    "google-site-verification": "Q1CXFjS4LoeATJZZmDq3iUY5hpOgG2_16oPF_DVp_h0",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* ✅ Google Site Verification */}
        <meta
          name="google-site-verification"
          content="Q1CXFjS4LoeATJZZmDq3iUY5hpOgG2_16oPF_DVp_h0"
        />
      </head>

      <body className={`${tinos.className} antialiased`}>
        {/* ✅ Google Analytics Script */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-3CRGRCBE0S"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-3CRGRCBE0S');
          `}
        </Script>

        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
